#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RoutePolicy {
    PublicReadOnly,
    OAuthCallbackPage,
    OAuthCompletion,
    AuthenticatedControl,
    Privileged,
}

pub const ROUTE_MANIFEST: &[(&str, &str, RoutePolicy)] = &[
    ("GET", "/", RoutePolicy::PublicReadOnly),
    ("GET", "/health", RoutePolicy::PublicReadOnly),
    ("GET", "/api/status", RoutePolicy::Privileged),
    ("GET", "/overlay/chat", RoutePolicy::PublicReadOnly),
    ("GET", "/overlay/events", RoutePolicy::PublicReadOnly),
    ("GET", "/overlay/kick-chat", RoutePolicy::PublicReadOnly),
    ("GET", "/overlay/kick-events", RoutePolicy::PublicReadOnly),
    ("GET", "/events-studio.html", RoutePolicy::PublicReadOnly),
    ("GET", "/dock/chat", RoutePolicy::PublicReadOnly),
    ("GET", "/dock/events", RoutePolicy::PublicReadOnly),
    ("GET", "/dock/kick-chat", RoutePolicy::PublicReadOnly),
    ("GET", "/dock/kick-events", RoutePolicy::PublicReadOnly),
    (
        "GET",
        "/auth/twitch/callback",
        RoutePolicy::OAuthCallbackPage,
    ),
    ("GET", "/auth/kick/callback", RoutePolicy::OAuthCallbackPage),
    (
        "GET",
        "/auth/streamelements/callback",
        RoutePolicy::OAuthCallbackPage,
    ),
    (
        "GET",
        "/config/:profile_id.json",
        RoutePolicy::PublicReadOnly,
    ),
    ("POST", "/api/chat/dock-config", RoutePolicy::Privileged),
    (
        "GET",
        "/api/events/dock-config",
        RoutePolicy::PublicReadOnly,
    ),
    ("POST", "/api/events/dock-config", RoutePolicy::Privileged),
    (
        "GET",
        "/api/chat/overlay-profiles",
        RoutePolicy::PublicReadOnly,
    ),
    (
        "GET",
        "/api/chat/overlay-config",
        RoutePolicy::PublicReadOnly,
    ),
    ("POST", "/api/chat/overlay-config", RoutePolicy::Privileged),
    (
        "DELETE",
        "/api/chat/overlay-config",
        RoutePolicy::Privileged,
    ),
    ("GET", "/api/twitch/auth-url", RoutePolicy::Privileged),
    (
        "POST",
        "/api/twitch/set-token",
        RoutePolicy::OAuthCompletion,
    ),
    (
        "POST",
        "/api/twitch/connection-key",
        RoutePolicy::Privileged,
    ),
    (
        "POST",
        "/api/twitch/use-connection",
        RoutePolicy::Privileged,
    ),
    (
        "POST",
        "/api/twitch/remove-connection",
        RoutePolicy::Privileged,
    ),
    ("POST", "/api/twitch/disconnect", RoutePolicy::Privileged),
    ("GET", "/api/kick/auth-url", RoutePolicy::Privileged),
    ("POST", "/api/kick/redeem", RoutePolicy::OAuthCompletion),
    ("POST", "/api/kick/disconnect", RoutePolicy::Privileged),
    ("POST", "/api/kick/chat", RoutePolicy::Privileged),
    ("GET", "/api/twitch/badges/all", RoutePolicy::PublicReadOnly),
    ("GET", "/api/twitch/emotes/all", RoutePolicy::PublicReadOnly),
    (
        "GET",
        "/api/events/overlay-profiles",
        RoutePolicy::PublicReadOnly,
    ),
    (
        "GET",
        "/api/events/overlay-config",
        RoutePolicy::PublicReadOnly,
    ),
    (
        "POST",
        "/api/events/overlay-config",
        RoutePolicy::Privileged,
    ),
    (
        "DELETE",
        "/api/events/overlay-config",
        RoutePolicy::Privileged,
    ),
    ("POST", "/api/events/test-alert", RoutePolicy::Privileged),
    (
        "GET",
        "/api/streamelements/session",
        RoutePolicy::Privileged,
    ),
    (
        "POST",
        "/api/streamelements/session",
        RoutePolicy::OAuthCompletion,
    ),
    (
        "DELETE",
        "/api/streamelements/session",
        RoutePolicy::Privileged,
    ),
    (
        "GET",
        "/api/streamelements/begin-login",
        RoutePolicy::Privileged,
    ),
    (
        "GET",
        "/api/streamelements/overlays",
        RoutePolicy::Privileged,
    ),
    (
        "POST",
        "/api/streamelements/import",
        RoutePolicy::Privileged,
    ),
    ("GET", "/ws/feed", RoutePolicy::PublicReadOnly),
    ("GET", "/ws/control", RoutePolicy::AuthenticatedControl),
    ("GET", "/google-fonts.css", RoutePolicy::PublicReadOnly),
    ("GET", "/google-fonts/file", RoutePolicy::PublicReadOnly),
    ("GET", "/fonts/*", RoutePolicy::PublicReadOnly),
    ("GET", "/events-media/*", RoutePolicy::PublicReadOnly),
    ("POST", "/api/chat/upload-font", RoutePolicy::Privileged),
    ("POST", "/api/events/upload-media", RoutePolicy::Privileged),
    (
        "POST",
        "/api/dock/issue-credential",
        RoutePolicy::Privileged,
    ),
    (
        "POST",
        "/api/dock/revoke-credential",
        RoutePolicy::Privileged,
    ),
];
